exclude: '(^|/)(Pipfile|Pipfile\.lock)$|alembic_test'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        # language_version: python3.11

  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.18.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-python-dateutil, types-dateparser, pandas-stubs]
  #       # language_version: python3.11
  - repo: local
    hooks:
    - id: mypy
      name: mypy  # run pytest (this is fine since small suite)
      entry: mypy --config-file mypy.ini src
      language: system        # uses your currently active venv
      pass_filenames: false   # run full suite (avoid passing changed files)
      always_run: true
      args:
        - --ignore-missing-imports
        - --show-error-codes
        - --pretty
        - --strict

  - repo: local
    hooks:
    - id: pytest
      name: pytest  # run pytest (this is fine since small suite)
      entry: pytest
      language: system        # uses your currently active venv
      pass_filenames: false   # run full suite (avoid passing changed files)
      always_run: true
      args:
        - --maxfail=1
        - -q
  # TODO: refactor
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       args: ["--convention=google"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
