"""set telegram id as index

Revision ID: 0c992a7fb56b
Revises: 568bc71138e4
Create Date: 2025-10-17 15:43:02.649865

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c992a7fb56b"
down_revision: Union[str, Sequence[str], None] = "568bc71138e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_telegram_id", "users", ["telegram_id"], unique=False)
    op.create_unique_constraint(None, "users", ["telegram_username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index("ix_users_telegram_id", table_name="users")
    # ### end Alembic commands ###
