"""add telegram username

Revision ID: 568bc71138e4
Revises: 1d8c90c1355f
Create Date: 2025-10-17 15:11:34.429382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "568bc71138e4"
down_revision: Union[str, Sequence[str], None] = "1d8c90c1355f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_username")
    # ### end Alembic commands ###
