"""set telegram username as not unique

Revision ID: 798577ab9098
Revises: 0c992a7fb56b
Create Date: 2025-10-17 15:45:33.648105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "798577ab9098"
down_revision: Union[str, Sequence[str], None] = "0c992a7fb56b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_telegram_username_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_telegram_username_key"),
        "users",
        ["telegram_username"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
