"""add telegram chat id

Revision ID: defa30e77acc
Revises: 798577ab9098
Create Date: 2025-10-18 10:50:15.065561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defa30e77acc'
down_revision: Union[str, Sequence[str], None] = '798577ab9098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False))
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id', 'telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
